// SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_RESET = 'SEARCH_RESET';

// FAVOURITE
export const ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAILED = 'ADD_FAVOURITE_FAILED';

export const REMOVE_FAVOURITE_REQUEST = 'REMOVE_FAVOURITE_REQUEST';
export const REMOVE_FAVOURITE_SUCCESS = 'REMOVE_FAVOURITE_SUCCESS';
export const REMOVE_FAVOURITE_FAILED = 'REMOVE_FAVOURITE_FAILED';